### ISSUE TITLE
Schema deletion + plan functionality

### ISSUE THREAD

**Issue by jrevillard** [domnikl/schema-registry-gitops#11]
Hello,

Thanks for this nice tool ! In your README you speak about the kafka-gitops analogy.

I see two differences mainly:
- there is no real "plan" functionality. Does the validate CLI option query the schema-registry to see if there is an update to do or not ?
- I played a bit and I see that if I remove a schema from the configuration, this later is not deleted from the schema registry: Is it intentional ? I personally prefer to have it removed but of course, I would need to be able to see it in a "plan" before

Best,
Jerome

**Comment by domnikl** [comment]
Hello Jerome,

first of all: thank you for considering schema-registry-gitops!

Right now, it does not really "plan" in the sense that it will check if there is an update to do. All it does is check if the changes are compatible. But it is on my roadmap to implement a real plan functionality like kafka-gitops does.

Not deleting anything is intentional as all the use cases I had where microservices where each service manages it's schemas itself and must not delete schemas that belong to other services. That is on the roadmap also, but it will not be default mode, rather be explicitely activated by a CLI switch.

Does that answer all your questions?

**Comment by jrevillard** [comment]
Hi @domnikl ,

Thanks a lot for the explanation !  My objective is a bit more strict indeed as I do not want the applications register or update the schema outside of the CI.

FYI, in the meantime, I just made a PR on kafka-gitops for this functionality if you are interested or just curious ;-) : https://github.com/devshawn/kafka-gitops/pull/76

Best,
Jerome

**Comment by domnikl** [comment]
I implemented plan and delete in the current master - replacing validate as that must be done implicitely anyways. Will release it as a new major version soon. Your PR is very interesting, tough, thanks for the link!

**Comment by jrevillard** [comment]
Really nice @domnikl !

Just as of curiosity, how did you do the diff ? I wanted to do it in my MR but did not had time yet.

Best,
Jerome
